Repository denysdovhan/ha-yasno-outages, pull requests merged in 2024-07, with the labels that each got.

#4 More sensors, translations, better codebase
  custom_components/yasno_outages/__init__.py
  custom_components/yasno_outages/api.py
  custom_components/yasno_outages/calendar.py
  custom_components/yasno_outages/const.py
  custom_components/yasno_outages/coordinator.py
  custom_components/yasno_outages/entity.py
  custom_components/yasno_outages/sensor.py
  custom_components/yasno_outages/translations/en.json
  custom_components/yasno_outages/translations/uk.json
  icons/icon.png
  icons/icon@2x.png
  icons/logo.png
  icons/logo@2x.png
Labels: enhancement

#5 fix next connectivity sensor
  custom_components/yasno_outages/coordinator.py
  custom_components/yasno_outages/sensor.py
Labels: bug

#6 fix: next connectivity state
  custom_components/yasno_outages/coordinator.py
Labels: bug

#8 Fixed group 2 Saturday schedule
  custom_components/yasno_outages/schedules/group-2.ics
Labels: bug

#10 Fix multi-day spanning events detection
  custom_components/yasno_outages/coordinator.py
Labels: bug

#12 Add support for Dnipro city
  contributing.md
  custom_components/yasno_outages/__init__.py
  custom_components/yasno_outages/api.py
  custom_components/yasno_outages/config_flow.py
  custom_components/yasno_outages/const.py
  custom_components/yasno_outages/coordinator.py
  custom_components/yasno_outages/schedules/group-1.ics
  custom_components/yasno_outages/schedules/group-2.ics
  custom_components/yasno_outages/schedules/group-3.ics
  custom_components/yasno_outages/schedules/group-4.ics
  custom_components/yasno_outages/schedules/group-5.ics
  custom_components/yasno_outages/schedules/group-6.ics
  custom_components/yasno_outages/translations/en.json
  custom_components/yasno_outages/translations/uk.json
Labels: enhancement

#13 Better typings updated manifest
  custom_components/yasno_outages/api.py
  custom_components/yasno_outages/config_flow.py
  custom_components/yasno_outages/coordinator.py
  custom_components/yasno_outages/entity.py
  custom_components/yasno_outages/manifest.json
  custom_components/yasno_outages/sensor.py
Labels: bug

#16 Fix next_connectivity and current_state sensors
  custom_components/yasno_outages/api.py
  custom_components/yasno_outages/coordinator.py
Labels: bug

#17 Improve check for intersecting intervals
  custom_components/yasno_outages/api.py
Labels: bug

#18 Add city selection config flow readme section
  readme.md
  readme.uk.md
Labels: documentation, chore
